import { useState } from 'react'

export type Goal = { id: string; title: string; sport: string; targetValue: number; currentValue: number; unit: string; targetDate: string | null; status: string }
export type GoalLog = { id: string; recordedValue: number; aiFeedback: string | null; recordedAt: string }

type Props = { goals: Goal[]; loading: boolean; selectedGoal: Goal | null; logs: GoalLog[]; onCreate: (goal: Omit<Goal, 'id' | 'currentValue' | 'status'>) => Promise<void>; onSelect: (goal: Goal) => Promise<void> }

export function Goals({ goals, loading, selectedGoal, logs, onCreate, onSelect }: Props) {
  const [title, setTitle] = useState(''); const [sport, setSport] = useState('Running'); const [target, setTarget] = useState(''); const [unit, setUnit] = useState('km'); const [targetDate, setTargetDate] = useState('')
  const submit = async () => { const targetValue = Number(target); if (!title.trim() || !Number.isFinite(targetValue) || targetValue <= 0) return; await onCreate({ title: title.trim(), sport, targetValue, unit, targetDate: targetDate || null }); setTitle(''); setTarget(''); setTargetDate('') }
  return <section className="content-section goals-page"><div className="goal-create-panel"><p className="eyebrow">NUEVO OBJETIVO</p><h2>Define un objetivo medible</h2><div className="goal-form"><label>Título<input value={title} onChange={event => setTitle(event.target.value)} placeholder="Ej. Correr una media maratón" /></label><label>Deporte<select value={sport} onChange={event => setSport(event.target.value)}><option>Running</option><option>Gimnasio</option><option>Natación</option><option>Personalizado</option></select></label><label>Valor objetivo<input type="number" min="0" step="0.1" value={target} onChange={event => setTarget(event.target.value)} placeholder="21" /></label><label>Unidad<input value={unit} onChange={event => setUnit(event.target.value)} placeholder="km, kg, repeticiones..." /></label><label>Fecha límite<input type="date" value={targetDate} onChange={event => setTargetDate(event.target.value)} /></label><button className="primary-button" onClick={() => void submit()}>Crear objetivo</button></div></div><div className="goals-layout"><div><div className="section-heading"><div><p className="eyebrow">SEGUIMIENTO</p><h2>Objetivos activos</h2></div><span>{goals.length}</span></div>{loading ? <div className="loading-state">Cargando objetivos…</div> : goals.length ? <div className="goal-list">{goals.map(goal => { const progress = Math.min(100, goal.targetValue > 0 ? goal.currentValue / goal.targetValue * 100 : 0); return <button className={`goal-card ${selectedGoal?.id === goal.id ? 'selected' : ''}`} key={goal.id} onClick={() => void onSelect(goal)}><div className="goal-card-heading"><span><strong>{goal.title}</strong><small>{goal.sport} · {goal.targetDate ? `Límite ${new Date(`${goal.targetDate}T12:00:00`).toLocaleDateString('es-ES')}` : 'Sin fecha límite'}</small></span><b>{goal.status === 'achieved' ? 'Conseguido' : `${Math.round(progress)}%`}</b></div><div className="goal-progress-track"><span style={{ width: `${progress}%` }} /></div><small>{goal.currentValue} / {goal.targetValue} {goal.unit}</small></button> })}</div> : <div className="history-empty"><strong>Aún no tienes objetivos.</strong><span>Crea el primero para empezar a medir tu progreso.</span></div>}</div>{selectedGoal && <div className="goal-history"><p className="eyebrow">HISTORIAL DE AVANCES</p><h2>{selectedGoal.title}</h2>{logs.length ? logs.map(log => <article className="goal-log" key={log.id}><div><strong>{log.recordedValue} {selectedGoal.unit}</strong><small>{new Date(log.recordedAt).toLocaleDateString('es-ES')}</small></div><p>{log.aiFeedback || 'Progreso registrado desde un entrenamiento.'}</p></article>) : <p className="detail-empty">Todavía no hay avances detectados para este objetivo.</p>}</div>}</div></section>
}
