/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from './lib/supabase'

type Exercise = { id: string; name: string; group: string; measurementType: 'reps_weight' | 'time_only' | 'time_weight' | 'reps_only'; sets: number; reps: number; weight: number; durationSeconds: number }
type PlannedItem = { id?: string; exerciseId: string; name: string; sets: number; targetReps: number | null; targetWeight: number | null; targetDuration: number | null }
type PlannedBlock = { id?: string; blockType: string; rounds: number; items: PlannedItem[] }
type Plan = { id: string; title: string; scheduledDate: string; status: 'scheduled' | 'in_progress' | 'completed'; blocks: PlannedBlock[] }
type LiveItem = PlannedItem & { completed: boolean; reps: number | null; weight: number | null; duration: number | null }

const statusLabel = { scheduled: 'Agendado', in_progress: 'En curso', completed: 'Completado' }

export function Plans({ userId, catalog }: { userId: string; catalog: Exercise[] }) {
  const [plans, setPlans] = useState<Plan[]>([]); const [selected, setSelected] = useState<Plan | null>(null); const [loading, setLoading] = useState(true)
  const [title, setTitle] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [exerciseId, setExerciseId] = useState(''); const [sets, setSets] = useState(3); const [reps, setReps] = useState(10); const [weight, setWeight] = useState(0)
  const [live, setLive] = useState<{ plan: Plan; startedAt: string; items: LiveItem[] } | null>(null); const [now, setNow] = useState(() => Date.now())
  const load = useCallback(async () => { setLoading(true); const { data, error } = await supabase.from('workout_plans').select('id,title,scheduled_date,plan_blocks(id,block_order,block_type,rounds,plan_items(id,exercise_id,target_reps,target_weight_kg,target_duration_seconds))').eq('user_id', userId).order('scheduled_date'); if (error) { window.alert(error.message); setLoading(false); return } setPlans((data ?? []).map((row: any) => ({ id: row.id, title: row.title, scheduledDate: row.scheduled_date, status: 'scheduled', blocks: (row.plan_blocks ?? []).sort((a: any,b: any) => a.block_order-b.block_order).map((block: any) => ({ id: block.id, blockType: block.block_type, rounds: block.rounds, items: (block.plan_items ?? []).map((item: any) => { const ex = catalog.find(e => e.id === item.exercise_id); return { id: item.id, exerciseId: item.exercise_id, name: ex?.name ?? 'Ejercicio', sets: 1, targetReps: item.target_reps, targetWeight: item.target_weight_kg, targetDuration: item.target_duration_seconds } }) })) }))); setLoading(false) }, [catalog, userId])
  useEffect(() => { void load() }, [load]); useEffect(() => { if (!live) return; const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer) }, [live])
  const addItem = () => { const ex = catalog.find(item => item.id === exerciseId); if (!ex) return; const next = { exerciseId: ex.id, name: ex.name, sets, targetReps: ex.measurementType.includes('reps') ? reps : null, targetWeight: ex.measurementType.includes('weight') ? weight : null, targetDuration: ex.measurementType.includes('time') ? 60 : null }; setSelected(current => current ? { ...current, blocks: current.blocks.length ? current.blocks.map((b,i) => i === 0 ? { ...b, items: [...b.items, next] } : b) : [{ blockType: 'Fuerza', rounds: 1, items: [next] }] } : null); setExerciseId('') }
  const create = async () => { if (!title.trim()) return; const { data, error } = await supabase.from('workout_plans').insert({ user_id: userId, title: title.trim(), scheduled_date: date }).select('id,title,scheduled_date').single(); if (error || !data) { window.alert(error?.message ?? 'No se pudo crear el plan'); return } const plan: Plan = { id: data.id, title: data.title, scheduledDate: data.scheduled_date, status: 'scheduled', blocks: [{ blockType: 'Fuerza', rounds: 1, items: [] }] }; setPlans(current => [...current, plan].sort((a,b) => a.scheduledDate.localeCompare(b.scheduledDate))); setSelected(plan); setTitle('') }
  const saveStructure = async () => { if (!selected) return; await supabase.from('plan_blocks').delete().eq('plan_id', selected.id); for (const [index, block] of selected.blocks.entries()) { const { data } = await supabase.from('plan_blocks').insert({ plan_id: selected.id, block_order: index + 1, block_type: block.blockType, rounds: block.rounds }).select('id').single(); if (!data) continue; const rows = block.items.map(item => ({ plan_block_id: data.id, exercise_id: item.exerciseId, target_reps: item.targetReps, target_weight_kg: item.targetWeight, target_duration_seconds: item.targetDuration })); if (rows.length) await supabase.from('plan_items').insert(rows) } await load(); window.alert('Plan guardado') }
  const start = async (plan: Plan) => { await supabase.from('workout_plans').update({ status: 'in_progress' }).eq('id', plan.id); setLive({ plan, startedAt: new Date().toISOString(), items: plan.blocks.flatMap(b => b.items.flatMap(item => Array.from({ length: Math.max(1,item.sets) }, () => ({ ...item, completed: false, reps: item.targetReps, weight: item.targetWeight, duration: item.targetDuration })))) }); setPlans(current => current.map(p => p.id === plan.id ? { ...p, status: 'in_progress' } : p)); setSelected(null) }
  const finish = async () => { if (!live) return; const workoutId = crypto.randomUUID(); const end = new Date(); const duration = Math.max(1, Math.round((end.getTime() - Date.parse(live.startedAt)) / 60000)); const { error } = await supabase.from('workouts').insert({ id: workoutId, user_id: userId, title: live.plan.title, type: 'Gimnasio', workout_date: live.plan.scheduledDate, duration_minutes: duration, plan_id: live.plan.id }); if (error) { window.alert(error.message); return } const { data: block } = await supabase.from('gym_blocks').insert({ workout_id: workoutId, block_order: 1, block_type: 'live', rounds: 1 }).select('id').single(); const completed = live.items.filter(item => item.completed); if (block && completed.length) await supabase.from('gym_logs').insert(completed.map((item,index) => ({ workout_id: workoutId, block_id: block.id, exercise_id: item.exerciseId, set_order: index + 1, round_number: 1, reps: item.reps, weight_kg: item.weight, duration_seconds: item.duration }))); await supabase.from('workout_plans').update({ status: 'completed' }).eq('id', live.plan.id); setLive(null); await load() }
  const elapsed = live ? Math.floor((now - Date.parse(live.startedAt)) / 1000) : 0; const grouped = useMemo(() => plans, [plans])
  if (live) return <LiveWorkout live={live} elapsed={elapsed} setLive={setLive} onFinish={() => void finish()} />
  return <section className="content-section plans-page"><div className="section-heading"><div><p className="eyebrow">AGENDA DE ENTRENAMIENTO</p><h2>Planifica tu próxima sesión</h2><p className="library-intro">Agenda entrenamientos concretos y ejecútalos en modo en vivo cuando llegue el momento.</p></div></div><div className="plan-create"><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Ej. Fuerza tren superior" /><input type="date" value={date} onChange={e => setDate(e.target.value)} /><button className="primary-button" onClick={() => void create()}>＋ Agendar entrenamiento</button></div>{loading ? <div className="loading-state">Cargando agenda…</div> : <div className="plans-list">{grouped.map(plan => <article className="plan-card" key={plan.id}><div><span className={`plan-status ${plan.status}`}>{statusLabel[plan.status]}</span><h3>{plan.title}</h3><p>{new Date(`${plan.scheduledDate}T12:00:00`).toLocaleDateString('es-ES', { weekday: 'long', day: 'numeric', month: 'long' })}</p><small>{plan.blocks.reduce((n,b) => n + b.items.length, 0)} ejercicios · {plan.blocks.length} bloques</small></div><div className="plan-actions"><button className="secondary-button" onClick={() => setSelected(plan)}>Editar estructura</button><button className="primary-button" disabled={plan.status === 'completed'} onClick={() => void start(plan)}>{plan.status === 'in_progress' ? 'Continuar' : 'Iniciar entrenamiento'}</button></div></article>)}</div>}{selected && <PlanEditor plan={selected} setPlan={setSelected} catalog={catalog} onAdd={addItem} onSave={() => void saveStructure()} onClose={() => setSelected(null)} />}</section>
}

function PlanEditor({ plan, setPlan, catalog, onAdd, onSave, onClose }: { plan: Plan; setPlan: (p: Plan) => void; catalog: Exercise[]; onAdd: () => void; onSave: () => void; onClose: () => void }) { return <div className="plan-editor"><div className="plan-editor-head"><h3>{plan.title}</h3><button className="close" onClick={onClose}>×</button></div>{plan.blocks.map((block,index) => <div className="planned-block" key={block.id ?? index}><input value={block.blockType} onChange={e => setPlan({ ...plan, blocks: plan.blocks.map((b,i) => i === index ? { ...b, blockType: e.target.value } : b) })} /><strong>{block.items.length} ejercicios</strong>{block.items.map((item,itemIndex) => <div className="planned-item" key={item.id ?? `${item.exerciseId}-${itemIndex}`}><span>{item.name}</span><small>{item.targetReps ? `${item.targetReps} reps` : item.targetDuration ? `${item.targetDuration}s` : ''}{item.targetWeight ? ` · ${item.targetWeight} kg` : ''}</small></div>)}</div>)}<select onChange={e => { if (e.target.value) { const ex = catalog.find(x => x.id === e.target.value); if (ex) { const item = { exerciseId: ex.id, name: ex.name, sets: 1, targetReps: ex.measurementType.includes('reps') ? 10 : null, targetWeight: ex.measurementType.includes('weight') ? 0 : null, targetDuration: ex.measurementType.includes('time') ? 60 : null }; setPlan({ ...plan, blocks: plan.blocks.map((b,i) => i === 0 ? { ...b, items: [...b.items, item] } : b) }) } } }}><option value="">Añadir ejercicio no planificado…</option>{catalog.map(ex => <option key={ex.id} value={ex.id}>{ex.name}</option>)}</select><div className="plan-editor-actions"><button className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" onClick={onSave}>Guardar estructura</button></div></div> }

function LiveWorkout({ live, elapsed, setLive, onFinish }: { live: { plan: Plan; startedAt: string; items: LiveItem[] }; elapsed: number; setLive: (v: any) => void; onFinish: () => void }) { return <div className="live-workout"><div className="live-header"><div><p className="eyebrow">MODO ENTRENO EN VIVO</p><h2>{live.plan.title}</h2></div><strong>{String(Math.floor(elapsed/60)).padStart(2,'0')}:{String(elapsed%60).padStart(2,'0')}</strong></div><p className="live-hint">Marca solo las series que realmente completes. Puedes ajustar cualquier valor antes de finalizar.</p>{live.items.map((item,index) => <div className={`live-set ${item.completed ? 'done' : ''}`} key={`${item.exerciseId}-${index}`}><button className="set-check" onClick={() => setLive({ ...live, items: live.items.map((x,i) => i === index ? { ...x, completed: !x.completed } : x) })}>{item.completed ? '✓' : '○'}</button><div><strong>{item.name}</strong><small>Objetivo: {item.targetReps ? `${item.targetReps} reps` : item.targetDuration ? `${item.targetDuration}s` : 'Ajustable'}</small></div><input type="number" value={item.reps ?? ''} placeholder="Reps" onChange={e => setLive({ ...live, items: live.items.map((x,i) => i === index ? { ...x, reps: e.target.value === '' ? null : Number(e.target.value) } : x) })} /><input type="number" value={item.weight ?? ''} placeholder="Kg" onChange={e => setLive({ ...live, items: live.items.map((x,i) => i === index ? { ...x, weight: e.target.value === '' ? null : Number(e.target.value) } : x) })} /></div>)}<div className="live-actions"><button className="secondary-button" onClick={() => setLive({ ...live, items: [...live.items, { exerciseId: 'custom', name: 'Ejercicio añadido', sets: 1, targetReps: null, targetWeight: null, targetDuration: null, completed: false, reps: null, weight: null, duration: null }] })}>＋ Añadir ejercicio</button><button className="primary-button" onClick={onFinish}>Finalizar entrenamiento</button></div></div> }
